"use server";

import Link from "next/link";
import clsx from "clsx";

interface UrlTablePaginationProps {
  offset: number;
  limit: number;
  totalCount: number;
  baseUrl: string;
  searchParams: { [key: string]: string | string[] | undefined }; // this is required, as we are going to append next page params on top of existing params
}

function getTotalNumberOfPage(limit: number, totalCount: number): number {
  return Math.ceil(totalCount / limit);
}

function getCurrentPage(offset: number, limit: number): number {
  return Math.floor(offset / limit) + 1;
}

function getBaseQueryString(searchParams: {
  [key: string]: string | string[] | undefined;
}): string {
  const baseParams = new URLSearchParams();

  Object.entries(searchParams).forEach(([key, value]) => {
    // offset and limit are generated by this component, so no need to consider these params
    if (key === "offset" || key === "limit") return;
    if (Array.isArray(value)) {
      value.forEach((v) => baseParams.append(key, v));
    } else if (value) {
      baseParams.set(key, value);
    }
  });

  return baseParams.toString();
}

function renderPageSizeLinks(currentLimit: number, urlToAppend: string) {
  const availableLimits = [10, 50, 100];
  return (
    <div>
      {availableLimits.map((limit) => (
        <Link
          key={`page-size-link-${limit}`}
          href={urlToAppend + `&offset=${0}&limit=${limit}`}
          className={clsx(
            "py-1 px-1.5 text-sm shadow-sm border -ml-px first:ml-0 first:rounded-l-md last:rounded-r-md",
            currentLimit === limit &&
              "text-white bg-slate-800 border-transparent"
          )}
        >
          {limit}
        </Link>
      ))}
    </div>
  );
}

function renderPageLinks(
  noOfPage: number,
  limit: number,
  currentPage: number,
  urlToAppend: string,
  linkStyle: string
) {
  const pageLinks = [];
  for (let i = 0; i < noOfPage; i++) {
    const offset = i * limit;
    const pageNo = i + 1;
    pageLinks.push(
      <Link
        key={`page-link-${offset}`}
        href={urlToAppend + `&offset=${offset}&limit=${limit}`}
        className={clsx(
          linkStyle,
          pageNo === currentPage && "bg-slate-800 text-white border-transparent"
        )}
      >
        {pageNo}
      </Link>
    );
  }
  return pageLinks;
}

export default async function UrlTablePagination({
  offset,
  limit,
  totalCount,
  baseUrl,
  searchParams,
}: UrlTablePaginationProps) {
  // calculate total number of page
  const noOfPage = getTotalNumberOfPage(limit, totalCount);
  // calculate current page
  const currentPage = getCurrentPage(offset, limit);
  // calculate we can go back to prev page
  const hasPrevious = currentPage > 1;
  // calculate we can go to next page
  const hasNext = currentPage < noOfPage;
  // get current base params
  const baseQueryString = getBaseQueryString(searchParams);

  // hide pagination footer if there is no record to show
  if (totalCount === 0) {
    return null;
  }

  // prepare url with existing other params
  const urlToAppend = baseUrl + "?" + baseQueryString;

  const pageSizeLinkStyle = "py-1 px-1.5 text-sm shadow-sm";

  const pageLinkStyle =
    "rounded-sm py-1.5 px-3 border text-sm shadow-sm mx-1 hover:bg-slate-300";

  const linkDisableStyle =
    "pointer-events-none opacity-50 cursor-not-allowed border-gray-400";

  return (
    <div className="flex space-between w-full py-2">
      <div className="flex items-center gap-2">
        <span>Show:</span>
        {renderPageSizeLinks(limit, urlToAppend)}
      </div>
      <div className="flex justify-end flex-2">
        <Link
          href={`${urlToAppend}&offset=${offset - limit}&limit=${limit}`}
          className={clsx(pageLinkStyle, !hasPrevious && linkDisableStyle)}
        >
          {"<"}
        </Link>
        {renderPageLinks(
          noOfPage,
          limit,
          currentPage,
          urlToAppend,
          pageLinkStyle
        )}
        <Link
          href={`${urlToAppend}&offset=${offset + limit}&limit=${limit}`}
          className={clsx(pageLinkStyle, !hasNext && linkDisableStyle)}
        >
          {">"}
        </Link>
      </div>
    </div>
  );
}
